[build]
  base = "focal"

baseurl = "https://relaxed-curie-6ab3e3.netlify.com/"
theme = "cocoa-eh-hugo-theme"
builddrafts = true
canonifyurls = true
contentdir = "content"
languageCode = "is"
layoutdir = "layouts"
publishdir = "public"
author = "Valtýr Sigurðsson"
title = "Valtýr, ýmsar pælingar"
disqusshortname = ""
pluralizelisttitles = false
disableKinds = ["taxonomy", "taxonomyTerm"]
enableEmoji = true

[permalinks]
  blog = "blog/:slug/"

[params]
  dateform = "Jan 2, 2006"
  dateformfull = "`r format(Sys.time(), '%e. %B %Y')`"
  description = "Blog"
  copyright = ""
  logofile = "img/iconid.png"
  faviconfile = "img/iconid.png"
  highlightjs = true
  progressively = false
  share = true
  latestpostcount = 5
  github = "harkanatta"
  email = "valtyrgullhjarta@gmail.com"
  social_banner = "img/banner.png"
  usesmallsummarycard = true
  posts_navigation = true
  small_banner_logo = false

  [params.utteranc]
    enable = true
    repo = "harkanatta/blogg"
    issueTerm = "title"

  [params.colors]
    identifier = "#527fc1f"
    identifier_dark = "#1a3152"
    trivial = "#6a7a8b"
    foreground = "#181d2a"
    background = "#f9f9f9"
    background_dark = "#282a36"
    code = "#87a5d2"
    type = "#97d28b"
    special = "#ffcb8d"
    value = "#96c2d7"
    statement = "#ff8e91"
