baseurl = "https://example.com/"
theme = "cocoa-eh-hugo-theme"
builddrafts = true
canonifyurls = true
contentdir = "content"
languageCode = "is"
layoutdir = "layouts"
publishdir = "public"
author = "Valtýr Sigurðsson"
title = " Sjávarlíffræði, R og fleira."
disqusshortname = ""
pluralizelisttitles = false
disableKinds = ["taxonomy", "taxonomyTerm"]

[permalinks]
blog = "blog/:slug/"

[params]
dateform = "Jan 2, 2006"
dateformfull = "`r format(Sys.time(), '%e. %B %Y')`"
description = "Example blog"
copyright = "Copyright © 2015-{year} Valtýr"
# copyrightUrl = "https://creativecommons.org/licenses/by-sa/4.0/"
logofile = "img/iconid.png"
faviconfile = "img/iconid.png"
highlightjs = true
progressively = false
share = true
# Share to googleplus, twitter, fb, linkedin by default
# disable by setting share_on_<social network> = false
# example: share_on_googleplus = false
latestpostcount = 5
github = "example"
email = "valtyrgullhjarta@gmail.com"
social_banner = "img/banner.png"
usesmallsummarycard = true
posts_navigation = true
# issoHost = "comments.domain.tld:1234"
# githubRepo = "githubUsername/repositoryName/tree/master"
small_banner_logo = false

[params.utteranc]
enable = true
repo = "harkanatta/blogg"
issueTerm = "title"

[params.colors]
identifier = "#527fc1f"
identifier_dark = "#1a3152"
trivial = "#6a7a8b"
foreground = "#181d2a"
background = "#f9f9f9"
background_dark = "#282a36"
code = "#87a5d2"
type = "#97d28b"
special = "#ffcb8d"
value = "#96c2d7"
statement = "#ff8e91"
