---
title: Sources of Microplastics in Iceland
author: Valtýr
date: '2020-02-10'
slug: sources-of-microplastics-in-iceland
categories:
  - R
tags: []
description: Desc
hacker_news_id: ''
lobsters_id: ''
meta_img: /images/image.jpg
---

The ministry of environment requested an estimate of microplastic pollution to Icelandic seas. The main goal was to obtain information about the main sources and pathways to be able to react with political action if necessary. A part of the goal was to write a overview on the state of knowledge about microplastics regarding the marine environment especially. The outcome was a report ([in Icelandic](https://harkanatta.github.io/orplastskyrslaUAR/)).

Around 80% of all microplastic pollution in Iceland is thought to originate from transportation of vehicles on rubber tires. Even though we haven't yet confirmed rubber tires in such great quantities in ocean sediments we theorise that rubber and road particles are washed to the sea with surface water from urban areas. There is no doubt these particles exist and persist in the environment. Other large sources stem from laundry and housepaint but most houses in Iceland have painted outside walls and roofs.

The main sources of microplastics in Iceland and pathways to soil, on the one hand and ocean, on the other hand, are represented in this interactive Sankey-diagram below.

```{r echo=FALSE, message=FALSE, warning=FALSE, cache=FALSE, out.height="100%"}
#losun <- (l+h)/2 #Meðaltal lægra og hærra mats á losun.
value <- c(371, 41, 26, 33.2, 60, 3, 0.2, 8.2, 0.34, 1, 0.002) #Uppspretta lægra mat
losun <- c(164, 5.7,  0, 15.2, 3.2, 0.3, 0, 8.2, 0.34, 0, 0.002) #losun lægra mat
#value <- c(379,586,38,233,21,48,3,11,8,32,0.3,3)
heiti <- c('Car tires ',
          'Road paint ',
          'Airplane tires ',
          'House paint ',
          'Ship paint ',
          'Artificial turf ',
          'Playgrounds ',
          'Laundry ',
          'Cosmetics ',
          'Hail shots ',
          'Landfill leachates ')
land <- value-losun
df <- data.frame(heiti,land,losun)
df <- df[order(df$heiti),]

library(networkD3)
nodes <- c(levels(df$heiti), 'Land','Sea')
nodes <- as.data.frame(nodes)
names(nodes) <- "name"

a <- list()
for (i in 1:nrow(df)) {
  a[i] <- list(rbind(matrix(c(df[i,c(2,3)]))))
}
b <- do.call("c",a)
value <- unlist(b)

links <- 
  data.frame(
    source=c(0,0,1,1,2,2,3,3,4,4,5,5,6,6,7,7,8,8,9,9,10,10),
    target=c(rep(c(11,12),11)),
    value=value)


Sank <- list(nodes, links)
names(Sank) <- c('nodes', 'links')
sn <- sankeyNetwork(
  Links = Sank$links,
  Nodes = Sank$nodes,
  Source = "source",
  Target = "target",
  Value = "value",
  NodeID = "name",
  units = "tonnes",
  colourScale = JS("d3.scaleOrdinal(d3.schemeCategory20);"),
  fontSize = 20,
  nodeWidth = 30, height = "681px", fontFamily = "Monospace"
)
rammi <- widgetframe::frameWidget(sn)
rammi

```

At Biopol thee has been monitoring on zooplankton and microplastics for a couple of years In Húnaflói bay, northern Iceland. There is little microplastic pollution because the area is sparsely inhabited. We mostly get fibers and flakes and half of them are possibly pollution from our boat and sampling equipment. Pollution of samples is difficult to avoid in microplastic research. We will soon gain accsess to a Raman spectro- microscope that will hopefully give us a further understanding about our samples.