---
title: Experiment with D3 and R markdown
author: Valtýr
date: '2020-01-23'
slug: experiment-with-d3-and-r-markdown
categories:
  - R
tags:
  - R
  - projects
  - d3
description: Desc
hacker_news_id: ''
lobsters_id: ''
meta_img: /images/image.jpg
css: styles.css
---

The visualization below was adapted from [GitHub here](https://github.com/jalapic/D3jsR/tree/master/regression). It represents measurements taken as a part of a monitoring program of some of the main catch species in Iceland.
 
----


```{r,  results="asis", message=FALSE, warning=FALSE, echo=T}
library(tidyverse)
allt <- read.csv("allt.csv")
fiskur <- allt %>% filter(MAELIADGERD == 3) %>% 
  select(c("TEGUND", "LENGD", "OSLAEGT")) %>% 
  na.omit()

fiskur$TEGUND <- ifelse(fiskur$TEGUND=="1","Gadus morhua",
       ifelse(fiskur$TEGUND=="2","Melanogrammus aeglefinus",
              "Other"))
#fiskur <- rbind(fiskur[fiskur$TEGUND=="Other",],fiskur[sample(1:dim(fiskur)[1],100),])

library(jsonlite)
cat(
  paste(
  '<script>
    var data = ',toJSON(fiskur),';
  </script>'
  , sep="")
)
```




<!--html_preserve-->
  <div><select id="selector"></select></div>
	<div class="chart"></div>
	<div class="equation"></div>
	<div class="equation"></div>
	<br/>
<!--/html_preserve-->

<script src="https://d3js.org/d3.v4.min.js"></script>
<script src="vizjs.js"></script>

The graph below has the desired power regression lines. This is useful for spotting outliers when skimming through the data. Next up for me is to figure out how to get the power curves into D3


```{r}

fiskur <- allt %>% filter(MAELIADGERD==3 & !is.na(OSLAEGT) & OSLAEGT!=0 & !is.na(LIFUR) & LIFUR!=0 & !is.na(LENGD) & TEGUND==1 & !is.na(SLAEGT) & SLAEGT!=0)

Logwl <- data.frame(logw = log(fiskur$OSLAEGT),logl = log(fiskur$LENGD))
Reg <- lm(Logwl$logw~Logwl$logl)

a <- Reg$coeff[1]
plot(fiskur$LENGD,fiskur$OSLAEGT, xlab = "Length (cm)", ylab = "Weight (g)")
q <- exp(a)
b <- Reg$coeff[2]
expw <- q * fiskur$LENGD^b
points(fiskur$LENGD,expw, pch=18, col='red')
sortlength <- sort(fiskur$LENGD)
expw2 <- q * sortlength^b
points(sortlength,expw2, type="l",col='red')
points(sortlength,expw2*1.35, type="l",col='blue')
points(sortlength,expw2*0.65, type="l",col='blue')

```
